

question_data=[
    {"category":"Mythology","type":"boolean","difficulty":"easy","question":"In Norse mythology, Thor once dressed as a woman.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Mythology","type":"boolean","difficulty":"easy","question":"According to Greek Mythology, Zeus can control lightning.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Mythology","type":"boolean","difficulty":"medium","question":"According to Norse mythology, Loki is a mother.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Mythology","type":"boolean","difficulty":"medium","question":"The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Mythology","type":"boolean","difficulty":"hard","question":"Rannamaari was a sea demon that haunted the people of the Maldives and had to be appeased monthly with the sacrifice of a virgin girl.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Mythology","type":"boolean","difficulty":"medium","question":"In Greek mythology, Hera is the goddess of harvest.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Mythology","type":"boolean","difficulty":"easy","question":"According to Greek Mythology, Atlas was an Olympian God.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Mythology","type":"boolean","difficulty":"medium","question":"The Roman god &quot;Jupiter&quot; was first known as &quot;Zeus&quot; to the Greeks.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Mythology","type":"boolean","difficulty":"easy","question":"A wyvern is the same as a dragon.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Mythology","type":"boolean","difficulty":"hard","question":"Janus was the Roman god of doorways and passageways.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Sports","type":"boolean","difficulty":"medium","question":"Soccer player Cristiano Ronaldo opened a museum dedicated to himself.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Sports","type":"boolean","difficulty":"easy","question":"Peyton Manning retired after winning Super Bowl XLIX.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Sports","type":"boolean","difficulty":"medium","question":"Tennis was once known as Racquetball.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Sports","type":"boolean","difficulty":"medium","question":"The Olympics tennis court is a giant green screen.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Sports","type":"boolean","difficulty":"easy","question":"Roger Federer is a famous soccer player.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Sports","type":"boolean","difficulty":"medium","question":"Formula E is an auto racing series that uses hybrid electric race cars.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Sports","type":"boolean","difficulty":"easy","question":"In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Sports","type":"boolean","difficulty":"medium","question":"During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Sports","type":"boolean","difficulty":"medium","question":"In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Sports","type":"boolean","difficulty":"easy","question":"There are a total of 20 races in Formula One 2016 season.","correct_answer":"False","incorrect_answers":["True"]},
   {"category":"Politics","type":"boolean","difficulty":"easy","question":"There was a satirical candidate named &quot;Deez Nuts&quot; running in the 2016 US presidential elections.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"Politics","type":"boolean","difficulty":"easy","question":"In 2016, the United Kingdom voted to stay in the EU.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Politics","type":"boolean","difficulty":"easy","question":"Russia passed a law in 2013 which outlaws telling children that homosexuals exist.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"Politics","type":"boolean","difficulty":"hard","question":"Joko Widodo has appeared in the cover of a TIME magazine.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Politics","type":"boolean","difficulty":"easy","question":"One of Barack Obama&#039;s United States presidential campaign slogan&#039;s was &quot;Yes We Can&quot;.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"Politics","type":"boolean","difficulty":"medium","question":"The State of Queensland, Australia voted NO to a referendum for daylight savings in 1992.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Politics","type":"boolean","difficulty":"easy","question":"Donald Trump won the popular vote in the 2016 United States presidential election.","correct_answer":"False","incorrect_answers":["True"]},
   {"category":"Politics","type":"boolean","difficulty":"hard","question":"Nazi Germany surrendered on Harry Truman&#039;s birthday while he was president.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"Politics","type":"boolean","difficulty":"hard","question":"George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Politics","type":"boolean","difficulty":"medium","question":"Jeb Bush was elected as Governor of Florida in 2002, starting his political career.","correct_answer":"False","incorrect_answers":["True"]},
   {"category":"History","type":"boolean","difficulty":"medium","question":"In World War II, Hawker Typhoons served in the Pacific theater.","correct_answer":"False","incorrect_answers":["True"]},
   {"category":"History","type":"boolean","difficulty":"medium","question":"The M41 Walker Bulldog remains in service in some countries to this day.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"History","type":"boolean","difficulty":"medium","question":"If you grab the bladed end of a longsword in a specific way, you will not cut yourself.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"History","type":"boolean","difficulty":"easy","question":"Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"History","type":"boolean","difficulty":"medium","question":"In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"History","type":"boolean","difficulty":"easy","question":"The United States of America declared their independence from the British Empire on July 4th, 1776.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"History","type":"boolean","difficulty":"medium","question":"The Hundred Years&#039; War was fought for more than a hundred years.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"History","type":"boolean","difficulty":"easy","question":"In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"History","type":"boolean","difficulty":"hard","question":"The USS Missouri (BB-63) last served in the Korean War.","correct_answer":"False","incorrect_answers":["True"]},
   {"category":"History","type":"boolean","difficulty":"hard","question":"The man that shot Alexander Hamilton was named Aaron Burr.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"Animals","type":"boolean","difficulty":"easy","question":"The Axolotl is an amphibian that can spend its whole life in a larval state.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"Animals","type":"boolean","difficulty":"easy","question":"A slug&rsquo;s blood is green.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"Animals","type":"boolean","difficulty":"medium","question":"&quot;Kamea,&quot; the Gilbertese Islander word for dog, is derived from the English phrase &quot;Come here!&quot;","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"Animals","type":"boolean","difficulty":"easy","question":"A flock of crows is known as a homicide.","correct_answer":"False","incorrect_answers":["True"]},
   {"category":"Animals","type":"boolean","difficulty":"easy","question":"The Killer Whale is considered a type of dolphin.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"Animals","type":"boolean","difficulty":"medium","question":"Finnish Lapphund dogs were used for herding reindeer.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"Animals","type":"boolean","difficulty":"easy","question":"Rabbits can see what&#039;s behind themselves without turning their heads.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"Animals","type":"boolean","difficulty":"medium","question":"You can tell the age of a ladybird by counting the spots on his back.","correct_answer":"False","incorrect_answers":["True"]},
   {"category":"Animals","type":"boolean","difficulty":"easy","question":"The internet browser Firefox is named after the Red Panda.","correct_answer":"True","incorrect_answers":["False"]},
   {"category":"Animals","type":"boolean","difficulty":"easy","question":"The freshwater amphibian, the Axolotl, can regrow it&#039;s limbs.","correct_answer":"True","incorrect_answers":["False"]}
]


